# Generated by Django 5.1.7 on 2025-07-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('processing', 'Processing'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
