# Generated by Django 5.1.6 on 2025-03-04 01:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='images'),
        ),
    ]
